spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/contas
#    username: postgres
#    password: senha
  
  # Chave secreta do JWT em formato plano para garantir a leitura correta
  jwt.secret.key: testesenhasecreta
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    schemas: contas
    locations: classpath:db/migration
  logging:
    level:
      org.flywaydb: DEBUG
